SELECT ii.ITEM_ID, ii.ITEM_NAME, ii.RARITY
FROM ITEM_INFO ii
JOIN ITEM_TREE it ON ii.ITEM_ID = it.ITEM_ID
JOIN ITEM_INFO parent ON parent.ITEM_ID = it.PARENT_ITEM_ID
WHERE parent.RARITY = "RARE"
ORDER BY ii.ITEM_ID DESC