-- 코드를 입력하세요
SELECT ugb.TITLE, ugb.BOARD_ID, ugr.REPLY_ID, ugr.WRITER_ID, ugr.CONTENTS, DATE_FORMAT(ugr.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
FROM USED_GOODS_BOARD ugb
RIGHT JOIN USED_GOODS_REPLY ugr ON ugr.BOARD_ID = ugb.BOARD_ID
WHERE ugb.CREATED_DATE LIKE '2022-10%'
ORDER BY ugr.CREATED_DATE, ugb.TITLE