SELECT 
  CONCAT(
    '/home/grep/src/', 
    COALESCE(ugf.BOARD_ID, ''), '/', 
    COALESCE(ugf.FILE_ID, ''), 
    COALESCE(ugf.FILE_NAME, ''), 
    COALESCE(ugf.FILE_EXT, '')
  ) AS FILE_PATH
FROM USED_GOODS_BOARD ugb
LEFT JOIN USED_GOODS_FILE ugf ON ugf.BOARD_ID = ugb.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC